# fly.toml app configuration file generated for cs375blueboard on 2024-08-10T19:55:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'cs375blueboard'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[env]
NODE_OPTIONS='--max-old-space-size=4096'
